###
POST http://interview.agileengine.com/auth
content-type: application/json

{
  "apiKey": "23567b218376f79d9415"
}

###
GET http://interview.agileengine.com/images
Authorization: Bearer 6d68db739ebc36131154d51fb472ed4a25da195a
content-type: application/json


###
GET http://interview.agileengine.com/images?page=3
Authorization: Bearer 6d68db739ebc36131154d51fb472ed4a25da195a
content-type: application/json

###
GET http://interview.agileengine.com/images/f3f6b4f4951ad19314cf
Authorization: Bearer 6d68db739ebc36131154d51fb472ed4a25da195a
content-type: application/json