###
POST http://interview.agileengine.com/auth
content-type: application/json

{
  "apiKey": "23567b218376f79d9415"
}

###
GET http://interview.agileengine.com/images
content-type: application/json


###
GET http://interview.agileengine.com/images?page=-1
Authorization: Bearer 9a7da82d2d5346adcebcb2cfb01f2c8757a09c5d
content-type: application/json

###
GET http://interview.agileengine.com/images/6f8dc3d33a8bb44d4fc31
Authorization: Bearer 9a7da82d2d5346adcebcb2cfb01f2c8757c09c5d
content-type: application/json