version: '3'
services:
  mongo:
    image: mongo:4.4.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  redis:
    image: redis:6.0.10-alpine
    ports:
      - 6379:6379

  public-api:
    image: image-gallery/public-api
    build:
      context: .
      dockerfile: src/AE.ImageGallery.PublicApi/Dockerfile
    depends_on:
      - redis
      - mongo
    ports:
      - 5000:80